// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"database/sql"
)

type Post struct {
	ID        int64        `json:"id"`
	Username  string       `json:"username"`
	Content   string       `json:"content"`
	CreatedAt sql.NullTime `json:"created_at"`
}
