// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: post.sql

package db

import (
	"context"
)

const createPost = `-- name: CreatePost :one
INSERT INTO post (
  username,content
) VALUES ($1,$2)
RETURNING id, username, content, created_at
`

type CreatePostParams struct {
	Username string `json:"username"`
	Content  string `json:"content"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, createPost, arg.Username, arg.Content)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}
