// Code generated by protoc-gen-go. DO NOT EDIT.
// source: login-user.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoginUserRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginUserRequest) Reset()         { *m = LoginUserRequest{} }
func (m *LoginUserRequest) String() string { return proto.CompactTextString(m) }
func (*LoginUserRequest) ProtoMessage()    {}
func (*LoginUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_811eaf06c4b289f1, []int{0}
}

func (m *LoginUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginUserRequest.Unmarshal(m, b)
}
func (m *LoginUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginUserRequest.Marshal(b, m, deterministic)
}
func (m *LoginUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginUserRequest.Merge(m, src)
}
func (m *LoginUserRequest) XXX_Size() int {
	return xxx_messageInfo_LoginUserRequest.Size(m)
}
func (m *LoginUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginUserRequest proto.InternalMessageInfo

func (m *LoginUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginUserResponse struct {
	User                 *UserChat `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LoginUserResponse) Reset()         { *m = LoginUserResponse{} }
func (m *LoginUserResponse) String() string { return proto.CompactTextString(m) }
func (*LoginUserResponse) ProtoMessage()    {}
func (*LoginUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_811eaf06c4b289f1, []int{1}
}

func (m *LoginUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginUserResponse.Unmarshal(m, b)
}
func (m *LoginUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginUserResponse.Marshal(b, m, deterministic)
}
func (m *LoginUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginUserResponse.Merge(m, src)
}
func (m *LoginUserResponse) XXX_Size() int {
	return xxx_messageInfo_LoginUserResponse.Size(m)
}
func (m *LoginUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginUserResponse proto.InternalMessageInfo

func (m *LoginUserResponse) GetUser() *UserChat {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterType((*LoginUserRequest)(nil), "pb.LoginUserRequest")
	proto.RegisterType((*LoginUserResponse)(nil), "pb.LoginUserResponse")
}

func init() { proto.RegisterFile("login-user.proto", fileDescriptor_811eaf06c4b289f1) }

var fileDescriptor_811eaf06c4b289f1 = []byte{
	// 185 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8e, 0x31, 0x8f, 0x82, 0x40,
	0x10, 0x85, 0x03, 0xb9, 0x5c, 0xee, 0xf6, 0xae, 0x00, 0x2a, 0x42, 0x85, 0xd8, 0xd8, 0xb8, 0x24,
	0x1a, 0xff, 0x80, 0x76, 0xc6, 0x8a, 0xc4, 0xc6, 0x6e, 0x17, 0x27, 0x40, 0x22, 0xcc, 0xb8, 0x33,
	0xc4, 0xbf, 0x6f, 0x16, 0xa3, 0xa1, 0x7c, 0xf3, 0xbd, 0xf9, 0xf2, 0x54, 0x74, 0xc3, 0xa6, 0x1b,
	0xd6, 0x23, 0x83, 0xd3, 0xe4, 0x50, 0x30, 0x09, 0xc9, 0x66, 0x71, 0xed, 0xc0, 0x08, 0xcc, 0xce,
	0xc5, 0x51, 0x45, 0x27, 0x5f, 0x3d, 0x33, 0xb8, 0x0a, 0xee, 0x23, 0xb0, 0x24, 0x99, 0xfa, 0xf1,
	0x8d, 0xc1, 0xf4, 0x90, 0x06, 0x79, 0xb0, 0xfa, 0xad, 0x3e, 0xd9, 0x33, 0x32, 0xcc, 0x0f, 0x74,
	0xd7, 0x34, 0x7c, 0xb1, 0x77, 0x2e, 0x76, 0x2a, 0x9e, 0xb9, 0x98, 0x70, 0x60, 0x48, 0x72, 0xf5,
	0xe5, 0x9f, 0x27, 0xd1, 0xdf, 0xe6, 0x5f, 0x93, 0xd5, 0x9e, 0x1f, 0x5a, 0x23, 0xd5, 0x44, 0xf6,
	0xcb, 0xcb, 0xa2, 0xe9, 0xa4, 0x1d, 0xad, 0xae, 0xb1, 0x2f, 0xd1, 0x1a, 0x46, 0x14, 0xec, 0xcb,
	0x06, 0xeb, 0xd6, 0x88, 0x21, 0x2a, 0xc9, 0xda, 0xef, 0x69, 0xee, 0xf6, 0x19, 0x00, 0x00, 0xff,
	0xff, 0xde, 0x73, 0x01, 0x9b, 0xd9, 0x00, 0x00, 0x00,
}
